### ISSUE TITLE
Make a budget for setting up a workshop in Zanskar

### ISSUE THREAD

**Issue by m-anish** [eka-foundation/home#1]
What are the tools, resources and money needed to make a workshop in Zanskar that can help support mesh networks there?

Make a budget for the same.

**Comment by m-anish** [comment]
Work on this lives [here](https://docs.google.com/spreadsheets/d/1a2oemhJFzckSZeLoR8aqLD9x4iuj0KiUWR05x0XMVz4/edit?usp=sharing).

**Comment by m-anish** [comment]
@sboruah Could you add a tab to the spreadsheet and make a budget for conducting workshops as you were mentioning in this week's call?

**Comment by mikkokotila** [comment]
This seems to be done. Shall we close?

**Comment by m-anish** [comment]
Oh yes!

**Comment by m-anish** [comment]
Thanks @mikkokotila @sboruah @Ishanchr @pdey for pulling through on this! 

The budget lives [here](https://docs.google.com/spreadsheets/d/1a2oemhJFzckSZeLoR8aqLD9x4iuj0KiUWR05x0XMVz4/edit#gid=0)
