### ISSUE TITLE
Add relevant details to README.md

### ISSUE THREAD

**Issue by m-anish** [eka-foundation/home#10]
We need to make README.md "camera ready". This issue will track progress.

**Comment by mikkokotila** [comment]
https://github.com/eka-foundation/home/blob/master/README.md

**Comment by m-anish** [comment]
Oh this is amazing! 

On the licensing aspect, since our logo lives in this repo, should we keep it CC-BY atleast? Or move the logo to a separate repo then.

**Comment by mikkokotila** [comment]
Once we have some illustrations, I think we can have nice README.md ... it was something I wanted to do for a long time. 

The rest was moved to #23

**Comment by m-anish** [comment]
Sounds good!

**Comment by m-anish** [comment]
Can you take this up after the website @mikkokotila 

- [ ] Make any enhancements to the readme as you feel like
- [ ] Replace CC0 with CC-BY-SA

**Comment by mikkokotila** [comment]
This is done alraedy. I think you have to clear cache, otherwise you end up seeing the old image.

**Comment by m-anish** [comment]
You just updated the link, but not the image. 

Anyway, these two commits fix this.. closing!
https://github.com/eka-foundation/home/commit/2aa6292895b8810f5ed92b7a010957f843e4bd8d
https://github.com/eka-foundation/home/commit/e52d151a54de5f1c9d03fca578a08789e7570415

**Comment by mikkokotila** [comment]
> You just updated the link, but not the image.

What do you mean by that? The image is just a link? 

EDIT: ah ok I get it.
