### ISSUE TITLE
jupyter4kids a.k.a Numerical Computing is Fun

### ISSUE THREAD

**Issue by mikkokotila** [eka-foundation/home#11]
I will work next on cleaning things up there and will then transfer the notebooks. There is also a video that could be made which is basically a talk I've done several times, which is about 10-15 minutes and basically just introduces the most basic vedic math concept but has the listener walking away feeling like they can count something like 34524 x 94324 in their head. Combined with the idea of "fog of war" as the primary block between ourselves and things that seem currently incredible and/or arguments regarding our capabilities that seem untenable.

**Comment by m-anish** [comment]
Feel free to assign a milestone to your work... 0.3 might be good :)

**Comment by mikkokotila** [comment]
I'll do the notebook clean up and move first. Also there are 3 unpublished notebooks, so we can do those on the first Monday of each month or something like that and maybe make it a monthly thing and keep improving the format.

**Comment by m-anish** [comment]
Sounds good. Once you do the initial port, we can join in.

**Comment by mikkokotila** [comment]
Done. Closing here.

**Comment by m-anish** [comment]
Great! For future reference, here is the [link](https://github.com/eka-foundation/numerical-computing-is-fun).
