### ISSUE TITLE
Move google doc minutes to github wiki? 

### ISSUE THREAD

**Issue by mikkokotila** [eka-foundation/home#12]
what do you think?

**Comment by m-anish** [comment]
You mean move minutes to wiki?
I am in favor of keeping it as a running log of things, to which a doc is better suited. The wiki can contain more crystallized info.

**Comment by m-anish** [comment]
We can revisit this in the future after a few weeks to see how things are going. Keeping open.

**Comment by m-anish** [comment]
Okay, so it's been three calls and five weeks, and I feel reasonably comfortable maintaining the minutes on the google document. So, for now, lets stick to that. Feel free to reopen this in the future if you want to change that.
