### ISSUE TITLE
Youtube channel art

### ISSUE THREAD

**Issue by m-anish** [eka-foundation/home#13]
I created a [youtube channel](https://www.youtube.com/channel/UCZqLHZKess48Kk42U4-Wl5g) where we may upload relevant videos we create down the line. To that end, a custom channel art would be great to have. [This link may be helpful.](https://support.google.com/youtube/answer/2972003?visit_id=636845236053718067-2484561800&p=picker_channel_art&hl=en&rd=1)

**Comment by m-anish** [comment]
@sboruah @mikkokotila, or anyone else watching this... 
help needed here :)

**Comment by so-ale** [comment]
@m-anish 
Where does the channel art go? any examples? 
Also, what are the dimensions for the image needed?

**Comment by m-anish** [comment]
Check [this link](https://support.google.com/youtube/answer/2972003?visit_id=636845236053718067-2484561800&p=picker_channel_art&hl=en&rd=1)

**Comment by m-anish** [comment]
@so-ale @sboruah @Ishanchr can someone cook up some quick mockups, so I can get started :) 

we can always improve things later. Feel free to assign the issue to yourself if you're working on it.

**Comment by m-anish** [comment]
Can look at providing access to the EKA youtube channel to tinker with channel art if you feel like

**Comment by m-anish** [comment]
@sboruah could you please commit to the [media](https://github.com/eka-foundation/media/tree/master/youtube-channel-art) repository, the three images you created for the eka.to website. The minimum resolution should be 2560x1440px. I will use them for the channel art. 

Alternatively, if you have the bandwidth, you can provide the images needed in this resolution as described [here](https://support.google.com/youtube/answer/2972003?hl=en-GB).

**Comment by m-anish** [comment]
Preliminary channel art added based on images given by @sboruah. Please visit the channel [here](https://www.youtube.com/channel/UCZqLHZKess48Kk42U4-Wl5g) 

Thoughts? (@mikkokotila @Ishanchr @sboruah @so-ale )

**Comment by m-anish** [comment]
This looks good enough for now. Closing.
