### ISSUE TITLE
Make a medium style blog for eka-foundation

### ISSUE THREAD

**Issue by m-anish** [eka-foundation/home#2]
We need to have a blog for eka-foundation, and it would be great if we could somehow do it via medium.

**Comment by mikkokotila** [comment]
For blog we already have some ready content [Things I Learned Building the Skynet](https://medium.com/@skynet.admin/things-i-learned-building-skynet-3033a4ce8992) and [How to Eat Dust](Things I Learned Building the Skynet PART 2 — How to Eat Dust) as well as [Dcentralize](http://dcentralize.net/) and [Thoughts on Pseudo decentralization](https://medium.com/@mikkokotila/thoughts-on-pseudo-decentralization-e07c306aa388). I'll see if I can access the original Skynet blog and we just take that over.

**Comment by m-anish** [comment]
Sounds good. 

Also it looks like medium.com deprecated custom domains [a while ago](https://help.medium.com/hc/en-us/articles/115003053487-Custom-Domains-service-deprecation). 

For what its worth, I am fine with having the blog be in medium.com. It will be more discoverable there.

**Comment by m-anish** [comment]
@mikkokotila has indicated that medium will give back access to the skynet blog, so waiting on that :)

**Comment by m-anish** [comment]
[Done](https://medium.com/eka-foundation). Thanks @mikkokotila
