### ISSUE TITLE
Copyright thread

### ISSUE THREAD

**Issue by mikkokotila** [eka-foundation/home#23]
From #10 

Related with the rights/claims/notice topic, the four options seem to be:

1. go with the current
2. change to cc-by (or other established one)
3. go back to modifying an established one
4. no claim whatsoever (not even cc public domain)

There is also the separate direction where different aspects might have different claim to it, but it seems more straightforward to have one pick and stick with it.

**Comment by m-anish** [comment]
I would go for CC-BY or CC-BY-NC (the latter if we want to be more restrictive.. for now). 

I am fine with either, as they are widely understood.

**Comment by mikkokotila** [comment]
For [CC-BY](https://creativecommons.org/licenses/by/2.0/) it says:

> No additional restrictions — You may not apply legal terms or technological measures that legally restrict others from doing anything the license permits.

There is a nuanced question here about how limiting this is in comparison to public. It seems that change is notable. For example, I imagine that in the future NGOs are increasingly replaced by "social enterprise" as well as all enterprises becoming more "social". I think is particularly true for smaller business. Trying to think about things from that standpoint, it seems cleaner to stay away from things that may become a problem later. For a person in that context, too many hard to answer questions are raised from reading such a passage as the one above. 

I think a type of claim to rights communicates two important things; this is the kind of use we want to encourage, and this is the kind of use we want to discourage. 

It seems that in the grander scheme of decisions, we're pretty much at the core of those decisions right now. It's kind of a bylaw. We believe that there should be so and so rights and this is how those rights are distributed.

**Comment by m-anish** [comment]
I see the CC-BY as a viral kind of license, and it does have lock-in in that sense. It says that we are engraving a certain value set in this licence and want to ensure that value set isn't compromised going further down the road. 

There is nothing in CC-BY that prevents for profit enterprises to spring up. I see it similar to GPL in a content - software sense, and I believe GPL plays a big part in the _current_ world that if you are looking to be a profit making enterprise, a certain amount of social responsibility is locked in. 

I believe that while we may be at the core of these discussions at this moment, we don't have the bandwidth to come up with the legalese required to form a new license that needs to be vetted and discussed by actual lawyers - I certainly don't, and I also don't know if EKA is the right vehicle to think about that (given the background of the people that are part of our community) - I do certainly encourage discussion on it and perhaps the crux of those discussions may be brought up with the bodies that are interested in this kind of thing. 

So, I believe the right course of action for us is to pick the closest safest proxy, and leave room for future discussion and changes. And in that, I think the CC-BY license keeps us reasonably 'safe'. If you strongly believe otherwise (i.e. we should go with CC0) I am okay with that too. 

Hope this makes sense. :-)

**Comment by mikkokotila** [comment]
Is there something that CC-BY materially adds (which is important to us) which is not there with CC0? Is CC0 missing something that CC-BY has?

**Comment by m-anish** [comment]
Yes!

CC0 means that the output of this work may be used in any which way, including for profit uses (like taking something public domain, making a tiny change to it, making it locked down/proprietary, and scaling up the alternative with capital investment), which may be detrimental to our mission.

CC-BY **ensures** this cannot happen to an extent.

**Comment by mikkokotila** [comment]
Yes, that is the established position behind CC-BY. I'm suggesting that there might be a fundamental flaw hidden in it. I think two observations have to do with this. 

1) CC is primarily designed / driven by not-for-profit forces
2) CC is created to solve an old world problem 

There are three important forces to consider first: 

- not-for-profits will be increasingly replaced by social enterprises 
- major corporates will make themselves appear more like social enterprises

Just like with anything else, some is good, and some is bad. That is the part we can't know. The way a for-profit, including high impact value-driven social enterprises, is incompatible to a far extent with legal complexity. Generally speaking, the smaller and earlier the entity is, the more averse they are towards legal complexity. This is not just irrationality, but there is a case to be made against something where you have to say where it's from or where you can't change the license terms in case you want to later. At the same time, the smaller the player, the more likely they are going to benefit from something someone like Eka can offer. Also, I think there is separate consideration which relates with the "good" vs "bad" aspect. Which is really what makes the argument about claiming rights in the first place. Basically wanting to avoid a case where things are used for bad. I'm not sure, but it's possible that it's easier for a small and early player to be genuinely good. Also there are many more small players than big players, and generally coming across something like Eka would be an individual somehow coming across it, so a company having just one person is enough. I think big companies generally say "let the legal dept take a look at it" but smaller players more like "hmmm...that seems confusing in the sense that I don't seem to have much capacity to predict how this might effect things later".

I understand what I'm saying is unpopular and even polemical. I guess my premise is that the current rights management best practices in the "open" side are mostly the handicraft of "purists" and also carry a certain degree of ideological baggage with them. 

I think it's important to consider worst case scenarios and then the most meaningful way to handle it given available resources in the short-term and maybe better later. Here though, we have to remember that upscaling rights claims retrospectively is not possible. I don't see any problem with downscaling when nothing new is added. 

Perhaps it's inevitable that have two questions to consider and answer. 

goal 1) make it as easy and frictionless to adopt available resources
goal 2) identify and legally eliminate worst case scenarios

Consider this how I might articulate a position related with this matter if was ready to do it. I'm by no means ready. I deeply appreciate the position you have articulated. For example breakthrough innovation in mesh-networking has important ramification to consider. But it's by no means straightforward with the current paradigm for rights management. For example, it seems that if we take the consideration, CC-BY is not going far enough because it does not actually limit apparent negative uses. It seems that the next upscale where rent-seeking is prohibited also falls short because it assumes for-profit bad, non-for-profit good. It seems that notice is like defense. We see a bunch of potential attacks and try to create protection against it. It's a very rough way to say it. It follows that we have to first ask the question about our sensitivity to error. Is it better to limit more with the cost that also good cases are blocked, or to limit less with the cost that some bad cases are not blocked. Again, that would be a very rough way to ask it?

**Comment by m-anish** [comment]
**EDIT: Please see this [first](https://github.com/eka-foundation/home/issues/23#issuecomment-462102936), then read the comment below.**

Tagging @holta This is a very interesting conversation! 

> goal 1) make it as easy and frictionless to adopt available resources
> goal 2) identify and legally eliminate worst case scenarios

100% agree with this. Let's keep discussing. 

The way I see it.. 

* CC-BY is well understood, or for that matter GPL (which is what I am suggesting all code be written in). Most existing work we are building off of is either one of those two licenses. This might become an issue if we are inheriting CC-BY or GPL'ed work for creating something as CC0.
* I don't think that someone starting out small will have any issues with those licenses. 
* It is very true these licenses are a response to the way the current world is organized. I feel my fingers shake a little when I think that my code written with a certain intent might be just taken up and used for whatever. There surely is a lot of baggage. :-) 
* I guess one question to ask is which would be easier. Going from CC0 to CC-BY if the need arose, or going from CC-BY to CC0?
* We still control the absolute right to allow anyone, any use. If a big corp wants CC0 kind of access, we are totally within our rights to grant them that. CC-BY doesn't affect that.
* To streamline things with CC-BY, we could say that all eka output is licensed by eka... i.e. CC-BY-EKA. This would be different from how it happens in many cases, where my creative work might be CC-BY-ANISH, or yours might be CC-BY-MIKKO. CC-BY-EKA would make changing licenses a single step process.  

Your idea _is_ .. radical :-) 
* It presupposes how things will turn out vis-a-vis nonprofits, corporations. Can you back those assumptions? 
* Do you think that those future social-enterprise corporations will operate under different legal bindings/structures that make the kind of use that I'm afraid of harder. What might those be?

I guess the TL;DR version of my comment might be.
Sure, if we lived in a world where all was CC0 (or even CC-BY), this wouldn't even be a question to consider. CC0 would make the most sense. But we don't live in that world, and I feel it worthwhile to have (atleast) some safeguards, which we can always forego later on. Also, it makes it easy for us to build off or GPL+CC-BY work, vast swathes of which already exist.

**Comment by m-anish** [comment]
With that said, we could adopt a policy like CC0-wherever-possible, which would still make it possible to work off of existing work and have it licensed accordingly, so it doesnt become a legal minefield

anyway, lets keep discussing.

**Comment by m-anish** [comment]
I **just** realized that all this while when I was saying CC-BY, I really meant CC-BY-SA.. which is more 'copyleft' GPL like. So please see this as a discussion between that and CC0 accordingly.

Sorry.

And in the context of this comment...
> No additional restrictions — You may not apply legal terms or technological measures that legally restrict others from doing anything the license permits.

CC-BY doesn't really restrict anything. I feel that was a blanket legal statement which doesn't have much meaning in context of CC-BY. It certainly has meaning in context of CC-BY-SA, where actual restrictions are placed. 

I wouldn't wanna go for CC-BY myself. It seems like an ego statement saying... hey, while you build your awesome product, just remember to put us in the credit roll. I don't really care about that whatsoever.

**Comment by mikkokotila** [comment]
Ok great, that simplifies the discussion. 

So first briefly on statements. It seems that any kind of right claim is a statement. To me it seems there are two different kinds of things being stated:

1) This is how I view the topic of ownership (explicit)
2) Here is who I think is good and who is bad (this is implicit) 

For the 2 it's worth noting that we don't actually have an explicit model to refer to when we adopt a given template (e.g. CC-BY-SA) but there is a strong innuendo. For example, generally speaking a commercial entity would have more considerations than an individual would. 

This is the part I'm trying to learn more about.


> * It presupposes how things will turn out vis-a-vis nonprofits, corporations. Can you back those assumptions?

Yes, we could open a thread where we go deeper into this topic as there are many valuable arguments to explore, as well as actual evidence. Or at least that is the way it appears currently when I'm writing this.

> * Do you think that those future social-enterprise corporations will operate under different legal bindings/structures that make the kind of use that I'm afraid of harder. What might those be?

I don't think so. I think they will look more like corporates today from the legal standpoint. I believe they will have a similar aversion towards risk, because they will largely spring out of corporates of today. But when we talk about aversion, I think it's important to ask the question like this: 

"Is no copyright claim at all a cause for greater aversion and than a permissive license?"

and 

"Is an unknown (custom) claim a cause for greater aversion than a permissive license?"

The answer may very well be "yes".

**Comment by m-anish** [comment]
Let me try and answer this particular question. 

> "Is an unknown (custom) claim a cause for greater aversion than a permissive license?"
>

I would venture to say, as I've said before (third para [here](https://github.com/eka-foundation/home/issues/23#issuecomment-461911173)), that I don't believe a custom license is a tangible option for us, atleast at this point, so this is a question for the future. 

This leaves us with:

> "Is no copyright claim at all a cause for greater aversion and than a permissive license?"
> 

I would first try and elaborate what 'aversion' means. Aversion to:
* Use our content?
* Build relationships with us?
* Identify uses which we think of as morally good? or bad?

Let's also look at the current situation - since that dictates our immediate moves. 
* For example, uploading a video on youtube, it offers two licenses. A restrictive Youtube license, and a more permissive CC-BY-SA license. It does not offer CC0. 
* For example, github doesn't offer any CC0 license by default when opening a repository.
* Most/All content we use on eka-related project iiab is all CC-BY-SA (or minor variations). 

In this context, saying we're CC-BY-SA, says, that we're a run of the mill organization that likes to create open content, and would like to see it shared - no qualms. 

In this context, saying we're CC0 for some work, CC-BY-SA for some other work (because we will create derivatives at some point), and somewhere in between (custom license) will create a mess and probably making someone averse to adopting out work without atleast asking us - why we're licensing things this way - an additional step many people might not bother with. 

Thoughts?

**Comment by mikkokotila** [comment]
> I would venture to say, as I've said before (third para [here](https://github.com/eka-foundation/home/issues/23#issuecomment-461911173)), that I don't believe a custom license is a tangible option for us, atleast at this point, so this is a question for the future.

May I entice you to engage in this matter without regard for outcome. I think when we are already focused on the outcome (this good, this not good) we tend to limit our thinking. In that light, what would you answer to the question then? Assuming there were no resource or other blocks. For the other question as well, I want to encourage you to think about it without any perceived blocks. 

To take away time or other sensitivity for this matter, how about we go ahead with CC-BY-SA across all assets, and continue this discussion on theoretical premise and see where it goes. What do you think?

**Comment by m-anish** [comment]
That is something I would love to take part in!

**Comment by m-anish** [comment]
I opened #30 to take this forward. 
@mikkokotila could you then, for now replace the CC0 with CC-BY-SA on the read-me and close this, while we discuss copyright more broadly.

**Comment by m-anish** [comment]
The remainder of this issue is being tracked in
* #10 for fixing the readme with the CC-CY-SA logo, and any other improvements
* #30 for the longer copyright discussion.

Closing this.
