### ISSUE TITLE
What tools are needed for Skynet build and maintenance?

### ISSUE THREAD

**Issue by mikkokotila** [eka-foundation/home#3]
Part of #1 but is something generally useful.

**Comment by m-anish** [comment]
@mikkokotila  Are we talking about actual on the ground tools (hardware, resources etc.) needed for on field deployment and maintenance, or about development tools - like compute resources, virtual machines, build servers, internet bandwidth?

The former is being tracked in #1

**Comment by mikkokotila** [comment]
I think here we are talking about build and maintenance tools. But it seems that it constitutes a thread of its own.

**Comment by m-anish** [comment]
So, maybe we can track the tools/expenses in a spreadsheet?

**Comment by mikkokotila** [comment]
sure

**Comment by m-anish** [comment]
Work on this now lives [here](https://docs.google.com/spreadsheets/d/1OaX6eQRHx79hJDySZjl5tM0q2TYgGv93DkAiioQwTgo/edit?usp=sharing).

**Comment by m-anish** [comment]
Okay, so I populated the sheet linked above with basic information. We also have a detailed list of things in the budget, so the purpose of this sheet is not super clear at this point. 

Nevertheless, we do have some kind of list here, and can always revisit it in case we need to. 

Closing!
