### ISSUE TITLE
Eka-foundation website design inputs

### ISSUE THREAD

**Issue by m-anish** [eka-foundation/home#4]
The following are required by @mikkokotila to make the website for eka-foundation:

* Palette
* Font
* Logo
* Icon?

**Comment by m-anish** [comment]
@sboruah has created a logo for the website, which we are using here as well. 
![eka](https://user-images.githubusercontent.com/5288668/51968337-b4978000-2497-11e9-81eb-0548c3a1b979.png)

**Comment by m-anish** [comment]
@mikkokotila is this done?

**Comment by mikkokotila** [comment]
@m-anish It's all good now. Next @sboruah is working on some line drawings to lively up the site.

**Comment by m-anish** [comment]
Please open a separate issue if you want to track it here. Closing this.
