### ISSUE TITLE
Carbon footprint of electronic devices

### ISSUE THREAD

**Issue by m-anish** [eka-foundation/home#7]
@mikkokotila in your carbon-footprint paper, did you have some kind of number for kgCO2e per USD of electronics?

eg: what would be the carbon footprint of a wifi router that costs $14 to purchase? What I am primarily interested in is the energy footprint of its production.

**Comment by m-anish** [comment]
Related to #6

**Comment by m-anish** [comment]
For what it's worth, I am using [this](https://calculator.carbonfootprint.com/calculator.aspx?tab=7) reference for calculations as of now

According to that for Radio/Telephone/Television the footprint is 0.34kg of CO2e per USD.

**Comment by m-anish** [comment]
[This](https://www.gov.uk/government/publications/greenhouse-gas-reporting-conversion-factors-2018) seems to be more comprehensive. I will revisit some conversion numbers.

**Comment by mikkokotila** [comment]
Maybe go through [this](https://www.sciencedirect.com/science/article/pii/S0195925517303505) first as it also involves review / critique of other methods. More importantly though, this is the method we developed specifically for the purpose of assessing energy footprint of internet networks (including content). You can remove the ads part though from the final calculations. It has a very extensive reference sections as well. It's better we follow this (or similar) as we created it for the purpose.

**Comment by m-anish** [comment]
Sure! Ill re-read the paper. Thanks!

**Comment by m-anish** [comment]
Okay, I will track further progress on this in #6 as this particular issue was opened with a specific question in mind.
