### ISSUE TITLE
Public access to EKA google drive

### ISSUE THREAD

**Issue by m-anish** [eka-foundation/home#8]
Do you have any issues with the following:

1. Make the EKA google drive public to the world?
2. Restrict write access to EKA members?

**Comment by pdey** [comment]
Can we have a public folder which is public to the world. It may be useful to keep private staff.. drafts and sensitive information such as contacts , machine access etc can be in private folders. Can be separate drives also.. whatever preferable and easier to manage.

**Comment by m-anish** [comment]
Exactly, I created EKA-private and EKA-public and you would have received invitations for both.

Does that work?

**Comment by pdey** [comment]
Sounds great!

**Comment by m-anish** [comment]
So, for closure, the eka-foundation public drive lives [here](https://drive.google.com/drive/folders/1Eoac32SYnjBRZAMkjRXW_v2dNUgWW2CI?usp=sharing).

**Comment by mikkokotila** [comment]
shall we have a wiki page here that has links to all the resources? Then also the other question is about the repos ... now we're in skynet repo with everything. Should we have one which is just 'general' or something like that? (which is kind of what we have now here) and then keep the project repos focused on the corresponding project (e.g. skynet)?

**Comment by m-anish** [comment]
Yeah, we should have some page.. wiki or otherwise. Wiki seems easiest for not. 

Also, I was originally thinking of calling this repo 'lounge' rather than skynet :)

But, agree, there should be a general repo, and then project focused ones, but I wanted to keep things simple until them become complex.
